/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlankWindow: typeof import('./components/windows/BlankWindow.vue')['default']
    copy: typeof import('./components/windows/HelloWorldWindow copy.vue')['default']
    HelloWorldWindow: typeof import('./components/windows/HelloWorldWindow.vue')['default']
    ProjectsWindow: typeof import('./components/windows/ProjectsWindow.vue')['default']
    WdDesktop: typeof import('./components/framework/WdDesktop.vue')['default']
    WdDesktopIcon: typeof import('./components/framework/WdDesktopIcon.vue')['default']
    WdTaskbar: typeof import('./components/framework/WdTaskbar.vue')['default']
    WdTopMenu: typeof import('./components/framework/WdTopMenu.vue')['default']
    WdTopMenuDropdown: typeof import('./components/framework/WdTopMenuDropdown.vue')['default']
    WdTopMenuItems: typeof import('./components/framework/WdTopMenuItems.vue')['default']
    WdWindow: typeof import('./components/framework/WdWindow.vue')['default']
  }
}
