/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelloWorldWindow: typeof import('./components/windows/HelloWorldWindow.vue')['default']
    WdDesktop: typeof import('./components/framework/WdDesktop.vue')['default']
    WdTaskbar: typeof import('./components/framework/WdTaskbar.vue')['default']
    WdTopMenu: typeof import('./components/framework/WdTopMenu.vue')['default']
    WdWindow: typeof import('./components/framework/WdWindow.vue')['default']
  }
}
